name: CI + CD

on:
  workflow_dispatch:

jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 156.67.80.49
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/frontend
            git pull
            npm install -f
            pm2 reload all

  Testing:
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: "test.hadielearning.com"
    needs: Staging
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 156.67.80.49
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/frontend
            git pull
            npm run build
            pm2 reload all

  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "hadielearning.com"
    needs: Testing
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 156.67.80.49
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/frontend
            git pull
            pm2 stop all
            npm run build
            pm2 reload all
